import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#b9ccb2",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        outline: "#84967e",
        "outline-variant": "#3b4b37",
        "surface-tint": "#00e639",
        primary: "#ebffe2",
        "on-primary": "#003907",
        "primary-container": "#00ff41",
        "on-primary-container": "#007117",
        "inverse-primary": "#006e16",
        secondary: "#c6c6c7",
        "on-secondary": "#2f3131",
        "secondary-container": "#454747",
        "on-secondary-container": "#b4b5b5",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#72ff70",
        "primary-fixed-dim": "#00e639",
        "on-primary-fixed": "#002203",
        "on-primary-fixed-variant": "#00530e",
        background: "#131313",
        "on-background": "#e2e2e2",
        "surface-variant": "#353535",
      },
      fontFamily: {
        display: ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-sm": ["JetBrains Mono", "monospace"],
        "code-snippet": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-snippet": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        base: "4px",
        "unit-1": "4px",
        "unit-2": "8px",
        "unit-4": "16px",
        "unit-8": "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
    },
  },
  plugins: [],
} satisfies Config;
