#!/usr/bin/env python3
"""Convert Qwen2.5-Coder-0.5B weights to Million archive format.

Two-phase approach:
  1. Quick test with first layer only (--quick)
  2. Full conversion of all weights (default)

Usage:
    python scripts/convert_qwen_to_million.py --quick   # first layer only
    python scripts/convert_qwen_to_million.py            # full model
"""
import sys, json, math, os, time, struct
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    from safetensors import safe_open
except ImportError:
    pass  # optional, we use manual reading for BF16

MODEL_URL = "https://huggingface.co/Qwen/Qwen2.5-Coder-0.5B/resolve/main/model.safetensors"
STATE_N = 1024     # nucleus state size: archive{state[1024], 8}
STATE_L = 8        # archive levels (parameter to unfold, not extra storage)

def get_qwen_config():
    return {
        "hidden_size": 896,
        "num_hidden_layers": 24,
        "num_attention_heads": 14,
        "num_key_value_heads": 2,
        "intermediate_size": 4864,
        "vocab_size": 151936,
        "tie_word_embeddings": True,
    }


def get_layer_weight_names(layer_num):
    prefix = f"model.layers.{layer_num}"
    return [
        f"{prefix}.input_layernorm.weight",
        f"{prefix}.self_attn.q_proj.weight",
        f"{prefix}.self_attn.q_proj.bias",
        f"{prefix}.self_attn.k_proj.weight",
        f"{prefix}.self_attn.k_proj.bias",
        f"{prefix}.self_attn.v_proj.weight",
        f"{prefix}.self_attn.v_proj.bias",
        f"{prefix}.self_attn.o_proj.weight",
        f"{prefix}.post_attention_layernorm.weight",
        f"{prefix}.mlp.gate_proj.weight",
        f"{prefix}.mlp.up_proj.weight",
        f"{prefix}.mlp.down_proj.weight",
    ]


def get_all_weight_names(config, max_layers=24):
    names = ["model.embed_tokens.weight"]
    for i in range(min(max_layers, config["num_hidden_layers"])):
        names.extend(get_layer_weight_names(i))
    names.append("model.norm.weight")
    return names


def compress_tensor(arr: np.ndarray, n=STATE_N) -> dict:
    """Compress a weight tensor into archive state[STATE_N] via strided sampling.
    archive{state[N], L} has N floats, not N*L — L is for unfold projection."""
    orig = arr.astype(np.float64)
    flat = orig.ravel()
    n_orig = len(flat)

    if n_orig <= n:
        data = np.pad(flat, (0, n - n_orig))
    else:
        step = max(1, n_orig // n)
        data = flat[::step][:n]
        if len(data) < n:
            data = np.pad(data, (0, n - len(data)))

    scale = float(max(np.abs(data).max(), 1e-10))
    data = data / scale * 0.95
    return {
        "state": data.tolist(),  # flat array of STATE_N values
        "scale": scale,
        "n_state": STATE_N,
        "n_levels": STATE_L,
    }


def download_file(url, dest, label="Downloading"):
    import requests
    dest = Path(dest)
    if dest.exists():
        print(f"  Using cached {dest.name}")
        return True

    print(f"\n  {label} {url.split('/')[-1]}...")
    resp = requests.get(url, stream=True, timeout=30)
    total = int(resp.headers.get("content-length", 0))
    downloaded = 0
    start = time.time()

    with open(dest, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)
                downloaded += len(chunk)
                if total > 0:
                    pct = downloaded / total * 100
                    elapsed = time.time() - start
                    speed = downloaded / 1024 / 1024 / max(elapsed, 1)
                    bar = "#" * int(pct / 5) + "." * (20 - int(pct / 5))
                    sys.stdout.write(f"\r  [{bar}] {pct:5.1f}% ({downloaded/1024/1024:.0f}/{total/1024/1024:.0f} MB, {speed:.1f} MB/s)")
                    sys.stdout.flush()
    print()
    return True


def generate_million_model(neurons, config, output_dir):
    """Generate the Qwen-Million model file."""
    models_dir = output_dir / "models"
    models_dir.mkdir(parents=True, exist_ok=True)

    n_layers = config["num_hidden_layers"]
    hidden = config["hidden_size"]
    vocab = config["vocab_size"]

    million_src = f"""// Qwen2.5-Coder-0.5B x Million hybrid model
// Auto-generated by convert_qwen_to_million.py
// {len(neurons)} archive nuclei from {sum(n['params'] for n in neurons):,} original parameters

let N_EMBED: int = 1
let N_LAYERS: int = {n_layers}
let HIDDEN: int = {hidden}
let VOCAB: int = {vocab}

// -- Nuclei definitions ------------------------------------------
nucleus embed_nucleus[N_EMBED] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus attn_q_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus attn_k_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus attn_v_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus attn_o_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus ffn_gate_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus ffn_up_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

nucleus ffn_down_nucleus[N_LAYERS] {{
  state: archive{{state[{1024}], {STATE_L}}}
  learning_mode: online
}}

// -- Helper functions --------------------------------------------
fn unfold(x: tensor[1024]) -> tensor[896] {{
  // Sinusoidal projection + tanh activation
  let result: tensor[896] = 0.0
  for i in 0..896 {{
    result[i] = tanh(x[i % 1024])
  }}
  return result
}}

fn compress(x: tensor[896]) -> tensor[1024] {{
  // Group average + tanh (inverse of unfold)
  let result: tensor[1024] = 0.0
  for i in 0..1024 {{
    let start: int = i * 896 / 1024
    let end: int = (i + 1) * 896 / 1024
    if end > 896 {{ end = 896 }}
    let sum: float = 0.0
    let count: int = end - start
    if count > 0 {{
      for j in start..end {{
        sum = sum + x[j]
      }}
      result[i] = tanh(sum / float(count))
    }}
  }}
  return result
}}

// -- Qwen transformer forward pass ------------------------------
fn forward(input_ids: tensor[seq_len]) -> tensor[VOCAB] {{
  // 1. Token embeddings
  let hidden: tensor[HIDDEN] = embed(input_ids)

  // 2. Transformer layers
  for layer in 0..N_LAYERS {{
    // Self-attention with GQA
    let residual: tensor[HIDDEN] = hidden
    let q: tensor[HIDDEN] = attn_q_nucleus[layer].forward(hidden)
    let k: tensor[128] = attn_k_nucleus[layer].forward(hidden)
    let v: tensor[128] = attn_v_nucleus[layer].forward(hidden)
    let attn_out: tensor[HIDDEN] = attn_o_nucleus[layer].forward(q, k, v)
    hidden = residual + attn_out

    // FFN (SwiGLU)
    let ffn_res: tensor[HIDDEN] = hidden
    let gate: tensor[HIDDEN] = ffn_gate_nucleus[layer].forward(hidden)
    let up: tensor[HIDDEN] = ffn_up_nucleus[layer].forward(hidden)
    let down: tensor[HIDDEN] = ffn_down_nucleus[layer].forward(gate * silu(up))
    hidden = ffn_res + down
  }}

  // 3. Final projection to vocabulary
  return hidden @ embed_nucleus[0].weight.T
}}

// -- Training ----------------------------------------------------
fn train(input_ids: tensor[seq_len], target_ids: tensor[seq_len]) -> float {{
  let logits: tensor[VOCAB] = forward(input_ids)
  let loss: float = cross_entropy(logits, target_ids)
  // STDP online update
  for layer in 0..N_LAYERS {{
    attn_q_nucleus[layer].stdp_update()
    attn_k_nucleus[layer].stdp_update()
    attn_v_nucleus[layer].stdp_update()
    attn_o_nucleus[layer].stdp_update()
    ffn_gate_nucleus[layer].stdp_update()
    ffn_up_nucleus[layer].stdp_update()
    ffn_down_nucleus[layer].stdp_update()
  }}
  return loss
}}

// -- Inference ---------------------------------------------------
fn generate(prompt: tensor[seq_len], max_tokens: int) -> tensor[max_tokens] {{
  let result: tensor[max_tokens] = 0
  let tokens: tensor[seq_len] = prompt
  for i in 0..max_tokens {{
    let logits: tensor[VOCAB] = forward(tokens)
    let next_token: int = argmax(logits)
    result[i] = next_token
    // Shift tokens
    for j in 0..seq_len-1 {{
      tokens[j] = tokens[j + 1]
    }}
    tokens[seq_len - 1] = next_token
  }}
  return result
}}
"""
    model_file = models_dir / "qwen_million.million"
    with open(model_file, "w") as f:
        f.write(million_src)
    return model_file


def generate_c_header(neurons, config, output_dir):
    """Generate C header with initialized nucleus states."""
    n_layers = config["num_hidden_layers"]
    hidden = config["hidden_size"]
    vocab = config["vocab_size"]

    weights_h = output_dir / "qwen_weights.h"
    with open(weights_h, "w") as f:
        f.write("/* Qwen2.5-Coder-0.5B -> Million archive initialization */\n")
        f.write("/* Auto-generated */\n\n")
        f.write(f"#define QWEN_N_NEURONS {len(neurons)}\n")
        f.write(f"#define QWEN_N_LAYERS {n_layers}\n")
        f.write(f"#define QWEN_HIDDEN {hidden}\n")
        f.write(f"#define QWEN_VOCAB {vocab}\n")
        f.write(f"#define QWEN_STATE_N {STATE_N}\n")
        f.write(f"#define QWEN_STATE_L {STATE_L}\n\n")

        total_orig = sum(n["params"] for n in neurons)
        total_arch = sum(n["n_state"] for n in neurons)
        f.write(f"// {len(neurons)} nuclei, {total_orig:,} params -> {total_arch:,} archive values\n\n")

        for i, n in enumerate(neurons):
            flat = n["state"]  # already flat list of STATE_N values
            f.write(f"// {n['weight_name']} shape={n['shape']} scale={n['scale']:.6f}\n")
            f.write(f"static float qwen_nucleus_{i}[{len(flat)}] = {{\n")
            for j in range(0, len(flat), 8):
                chunk = flat[j:j+8]
                vals = ", ".join(f"{v:.8f}f" for v in chunk)
                f.write(f"  {vals},\n")
            f.write("};\n\n")

    return weights_h


def convert(quick=False):
    config = get_qwen_config()
    weights_dir = ROOT / "build" / "qwen_weights"
    weights_dir.mkdir(parents=True, exist_ok=True)
    output_dir = ROOT / "build" / "qwen_million"
    output_dir.mkdir(parents=True, exist_ok=True)

    max_layers = 1 if quick else config["num_hidden_layers"]
    weight_names = get_all_weight_names(config, max_layers)

    print(f"Qwen2.5-Coder-0.5B -> Million Converter")
    print("=" * 60)
    print(f"  Mode:  {'quick (layer 0)' if quick else 'full'}")
    print(f"  Tensors: {len(weight_names)}")
    print(f"  Archive: state[1024] x {STATE_L} = {STATE_N} values/nucleus")

    # Download full model (even in quick mode we can download in background)
    model_path = weights_dir / "model.safetensors"
    if not model_path.exists() or model_path.stat().st_size < 1000000:
        download_file(MODEL_URL, model_path)
    else:
        print(f"  Using existing weights ({model_path.stat().st_size / 1024 / 1024:.0f} MB)")

    # Convert weights
    print(f"\n  Converting {max_layers} layer(s)...")
    neurons = []

    # Read safetensors header (JSON) and raw bytes manually for BF16 support
    with open(str(model_path), "rb") as f_safe:
        hdr_len = struct.unpack("<Q", f_safe.read(8))[0]
        hdr = json.loads(f_safe.read(hdr_len).decode("utf-8"))
        tensors_meta = {k: v for k, v in hdr.items() if k != "__metadata__"}

        for name in weight_names:
            if name not in tensors_meta:
                print(f"  Warning: {name} not found, skipping")
                continue

            info = tensors_meta[name]
            shape = info["shape"]
            offsets = info["data_offsets"]
            dtype_str = info["dtype"]
            nparams = int(np.prod(shape))

            # Read raw bytes at tensor offset
            f_safe.seek(8 + hdr_len + offsets[0])
            raw = f_safe.read(offsets[1] - offsets[0])

            # Convert to float32 (handles BF16, F16, F32)
            if dtype_str == "BF16":
                # BF16 -> uint16 -> shift left 16 -> view as float32
                data_uint16 = np.frombuffer(raw, dtype=np.uint16)
                tensor = (data_uint16.astype(np.uint32) << 16).view(np.float32).reshape(shape)
            elif dtype_str == "F16":
                data_uint16 = np.frombuffer(raw, dtype=np.uint16)
                tensor = data_uint16.view(np.float16).astype(np.float32).reshape(shape)
            elif dtype_str == "F32":
                tensor = np.frombuffer(raw, dtype=np.float32).reshape(shape)
            else:
                # Fallback: try safetensors library
                with safe_open(str(model_path), framework="np", device="cpu") as f_safe2:
                    tensor = f_safe2.get_tensor(name).astype(np.float32)
                print(f"  Using safetensors fallback for {name}")

            compressed = compress_tensor(tensor)

            neurons.append({
                "name": f"qwen_{name.replace('.', '_')}",
                "weight_name": name,
                "shape": shape,
                "dtype": dtype_str,
                "params": nparams,
                "scale": compressed["scale"],
                "state": compressed["state"],
                "n_state": compressed["n_state"],
                "n_levels": compressed["n_levels"],
            })

            pct = len(neurons) / len(weight_names) * 100
            print(f"    [{pct:5.1f}%] {name}: {shape} -> {STATE_N} values ({nparams/STATE_N:.0f}x)")

    # Generate outputs
    header_file = generate_c_header(neurons, config, output_dir)
    # Also generate topology JSON
    topo_path = output_dir / "qwen_topology.json"
    json.dump({
        "config": config,
        "neurons": [{
            "name": n["weight_name"],
            "shape": n["shape"],
            "scale": n["scale"],
            "dtype": n["dtype"],
        } for n in neurons],
    }, open(topo_path, "w"), indent=2)

    total_orig = sum(n["params"] for n in neurons)
    total_arch = sum(n["n_state"] for n in neurons)
    ratio = total_orig / max(total_arch, 1)

    print(f"\n  Summary:")
    print(f"    Original parameters: {total_orig:,}")
    print(f"    Archive values:      {total_arch:,}")
    print(f"    Compression ratio:   {ratio:.1f}x")
    print(f"    Topology:            {topo_path}")
    print(f"    C header:            {header_file}")
    print(f"\n  Done!\n")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--quick", action="store_true", help="Convert only first layer")
    args = parser.parse_args()
    convert(quick=args.quick)
