"""Generate portable C runtime from Million MIR (event-driven)."""

from __future__ import annotations

import re
from pathlib import Path

from compiler import __version__
from compiler.codegen.c_backprop import CBackpropEmitter
from compiler.codegen.c_bptt import CBPTTEmitter
from compiler.codegen.c_event import CEventEmitter
from compiler.codegen.dynamics import DynamicsCodegen
from compiler.ir.million_ir import MIRNeuron, MIRRegion, MIRTrain


class CCodeGen:
    def __init__(self, mir_module, source_dir: Path | None = None):
        self.module = mir_module
        self.source_dir = source_dir or Path(".")
        self.indent = 0
        self.lines: list[str] = []
        self._steps = mir_module.simulation_steps

    def emit(self, line: str = ""):
        prefix = "    " * self.indent if line else ""
        self.lines.append(f"{prefix}{line}")

    def _set_indent(self, n: int):
        self.indent = n

    def generate(self) -> str:
        self._emit_header()
        self._emit_functions()
        self._emit_types()
        self._emit_neuron_structs()
        self._emit_archive_ops()
        self._emit_tensor_ops()
        CBackpropEmitter(self.emit).emit_block()
        self._emit_learning_rules()
        self._emit_neuron_processors()
        ev = CEventEmitter(self.emit, self._set_indent, self)
        ev.emit_globals()
        ev.emit_queue_helpers()
        self._emit_regions(ev)
        self._emit_datasets()
        self._emit_training()
        self._emit_inference(ev)
        self._emit_main(ev)
        return "\n".join(self.lines)

    def _emit_header(self):
        self.emit("/* ======================================== */")
        self.emit(f"/*  Generated by Million Compiler v{__version__}  */")
        self.emit("/*  Event-driven runtime + hybrid learning   */")
        self.emit("/* ======================================== */")
        self.emit()
        self.emit("#include <stdio.h>")
        self.emit("#include <stdlib.h>")
        self.emit("#include <string.h>")
        self.emit("#include <math.h>")
        self.emit("#include <time.h>")
        self.emit()

    def _emit_types(self):
        self.emit("typedef struct {")
        self.emit("    float potential; float threshold; float refractory; int refr_counter;")
        self.emit("} Membrane;")
        self.emit()

    def _emit_neuron_structs(self):
        for neuron in self.module.neurons:
            self.emit(f"typedef struct Neuron_{neuron.name} Neuron_{neuron.name};")
        self.emit()
        for neuron in self.module.neurons:
            self.emit(f"struct Neuron_{neuron.name} {{")
            self.indent += 1
            self.emit(f"float nucleus[{neuron.nucleus_size}];")
            self.emit("Membrane mem;")
            self.emit("float output;")
            self.indent -= 1
            self.emit("};")
            self.emit()
            self.emit(f"void init_{neuron.name}(Neuron_{neuron.name}* n) {{")
            self.indent += 1
            self.emit("memset(n->nucleus, 0, sizeof(n->nucleus));")
            self.emit(f"n->mem.potential = {neuron.membrane_potential}f;")
            self.emit("n->mem.threshold = 1.0f;")
            self.emit(f"n->mem.refractory = {neuron.refractory_period}f;")
            self.emit("n->mem.refr_counter = 0;")
            self.emit("n->output = 0.0f;")
            self.indent -= 1
            self.emit("}")
            self.emit()

    def _emit_archive_ops(self):
        self.emit("void archive_unfold(float* in, int in_size, float* out, int out_size, int level) {")
        self.indent += 1
        self.emit("for (int i = 0; i < out_size; i++) {")
        self.indent += 1
        self.emit("float sum = 0.0f;")
        self.emit("for (int j = 0; j < in_size; j++)")
        self.emit("    sum += in[j] * sinf((float)(i * j + level));")
        self.emit("out[i] = tanhf(sum / (float)in_size);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()
        self.emit("void archive_compress(float* in, int in_size, float* out, int out_size) {")
        self.indent += 1
        self.emit("int group = in_size / out_size;")
        self.emit("if (group < 1) group = 1;")
        self.emit("for (int i = 0; i < out_size; i++) {")
        self.indent += 1
        self.emit("float sum = 0.0f;")
        self.emit("int start = i * group;")
        self.emit("for (int j = 0; j < group && (start + j) < in_size; j++)")
        self.emit("    sum += in[start + j];")
        self.emit("out[i] = tanhf(sum / (float)group);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()

    def _emit_tensor_ops(self):
        self.emit("/* ========= Tensor Operations ========= */")
        self.emit("void tensor_add(float* a, float* b, float* out, int n) {")
        self.indent += 1
        self.emit("for (int i = 0; i < n; i++) out[i] = a[i] + b[i];")
        self.indent -= 1
        self.emit("}")
        self.emit()
        self.emit("void tensor_mul(float* a, float* b, float* out, int n) {")
        self.indent += 1
        self.emit("for (int i = 0; i < n; i++) out[i] = a[i] * b[i];")
        self.indent -= 1
        self.emit("}")
        self.emit()
        self.emit("void tensor_dot(float* a, float* b, int n) {")
        self.indent += 1
        self.emit("float sum = 0.0f;")
        self.emit("for (int i = 0; i < n; i++) sum += a[i] * b[i];")
        self.emit("return sum;")
        self.indent -= 1
        self.emit("}")
        self.emit()

    def _emit_learning_rules(self):
        self.emit("void apply_hebbian(float* nucleus, int size, float* input, int input_size,")
        self.emit("    float output, float lr) {")
        self.indent += 1
        self.emit("for (int i = 0; i < size && i < input_size; i++) {")
        self.indent += 1
        self.emit("nucleus[i] += lr * input[i] * output;")
        self.emit("nucleus[i] = tanhf(nucleus[i]);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()
        self.emit("void apply_stdp(float* nucleus, int size, float* input, int input_size,")
        self.emit("    float output, float lr) {")
        self.indent += 1
        self.emit("float dt = output - 0.5f;")
        self.emit("for (int i = 0; i < size && i < input_size; i++) {")
        self.indent += 1
        self.emit("float dw = lr * input[i] * dt * expf(-fabsf((float)i * dt));")
        self.emit("nucleus[i] += dw;")
        self.emit("nucleus[i] = tanhf(nucleus[i]);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()

    def _process_neuron(self, neuron: MIRNeuron):
        ns = neuron.nucleus_size
        dyn = DynamicsCodegen(neuron)
        allocs, dyn_lines, compressed, malloc_vars = dyn.generate()
        has_dynamics = bool(neuron.dynamics)
        state_var = f"state_{neuron.name}"
        fired_var = f"fired_{neuron.name}"

        self.emit(
            f"int process_{neuron.name}(Neuron_{neuron.name}* n, float* input_vec,"
            f" int input_size) {{"
        )
        self.indent += 1

        if has_dynamics:
            for a in allocs:
                self.emit(a)
            for line in dyn_lines:
                self.emit(line)
            if compressed and compressed.startswith("compressed_"):
                self.emit(f"float {state_var}[{ns}];")
                self.emit(f"memcpy({state_var}, {compressed}, sizeof({state_var}));")
            elif compressed and compressed.startswith("dyn_tmp"):
                self.emit(f"float {state_var}[{ns}];")
                l2 = ns * neuron.archive_levels * ns
                self.emit(f"archive_compress({compressed}, {l2}, {state_var}, {ns});")
            else:
                self.emit(f"float {state_var}[{ns}];")
                self.emit(f"memcpy({state_var}, n->nucleus, sizeof({state_var}));")
        else:
            self.emit(f"float {state_var}[{ns}];")
            self.emit(f"memcpy({state_var}, n->nucleus, sizeof({state_var}));")

        self.emit("if (n->mem.refr_counter > 0) {")
        self.indent += 1
        self.emit("n->output = 0.0f;")
        self.emit("goto process_cleanup;")
        self.indent -= 1
        self.emit("}")

        self.emit("float delta = input_vec[0];")
        self.emit("if (input_size > 1) {")
        self.indent += 1
        self.emit("delta = 0.0f;")
        self.emit("for (int i = 0; i < input_size; i++)")
        self.emit(f"    delta += input_vec[i] * {state_var}[i % {ns}];")
        self.emit("delta /= (float)input_size;")
        self.indent -= 1
        self.emit("}")
        self.emit("n->mem.potential += delta;")
        self.emit("if (n->mem.potential >= n->mem.threshold) {")
        self.indent += 1
        self.emit("n->output = n->mem.potential;")
        self.emit("n->mem.potential = 0.0f;")
        self.emit("n->mem.refr_counter = (int)n->mem.refractory;")
        if neuron.membrane_threshold == "adaptive":
            self.emit(
                "n->mem.threshold = 0.5f + (n->mem.threshold - 0.5f) * 0.9f"
                " + 0.1f * fabsf(n->output);"
            )
        self.indent -= 1
        self.emit("} else {")
        self.indent += 1
        self.emit("n->output = 0.0f;")
        self.emit("n->mem.potential *= 0.95f;")
        self.indent -= 1
        self.emit("}")

        self.emit(f"int {fired_var} = (n->output > 0.0f) ? 1 : 0;")
        self.emit("process_cleanup:")
        for var in malloc_vars:
            self.emit(f"free({var});")
        self.emit(f"return {fired_var};")
        self.indent -= 1
        self.emit("}")
        self.emit()
        self._emit_hybrid_step(neuron)

    def _emit_hybrid_step(self, neuron: MIRNeuron):
        ns = neuron.nucleus_size
        l1 = ns * neuron.archive_levels
        self.emit(
            f"void train_step_hybrid_{neuron.name}(Neuron_{neuron.name}* n,"
            f" float* input, float target, float lr, float stdp_lr) {{"
        )
        self.indent += 1
        self.emit(f"float fwd_l1[{l1}];")
        self.emit(f"float fwd_out[{ns}];")
        self.emit(f"float grad_out[{ns}];")
        self.emit(f"float grad_nuc[{ns}];")
        self.emit(f"archive_unfold(n->nucleus, {ns}, fwd_l1, {l1}, 1);")
        self.emit(f"archive_compress(fwd_l1, {l1}, fwd_out, {ns});")
        self.emit("float loss = fwd_out[0] - target;")
        self.emit(f"for (int gi = 0; gi < {ns}; gi++)")
        self.emit("    grad_out[gi] = (gi == 0) ? (2.0f * loss) : 0.0f;")
        self.emit(
            f"archive_unfold_grad(n->nucleus, {ns}, fwd_l1, {l1}, 1, grad_out, grad_nuc);"
        )
        self.emit(f"for (int gi = 0; gi < {ns}; gi++) n->nucleus[gi] -= lr * grad_nuc[gi];")
        self.emit(
            f"apply_stdp(n->nucleus, {ns}, input, {ns}, n->output, stdp_lr);"
        )
        self.indent -= 1
        self.emit("}")
        self.emit()

    def _emit_online_learning(self):
        for neuron in self.module.neurons:
            if neuron.learning_mode == "online":
                self.emit(f"void online_step_{neuron.name}(Neuron_{neuron.name}* n,")
                self.emit(f"    float* input, float lr, float stdp_lr) {{")
                self.indent += 1
                ns = neuron.nucleus_size
                self.emit(f"// Online learning: infer + train on each step")
                self.emit(f"float fwd_l1[{ns * neuron.archive_levels}];")
                self.emit(f"float fwd_out[{ns}];")
                self.emit(f"archive_unfold(n->nucleus, {ns}, fwd_l1, {ns * neuron.archive_levels}, 1);")
                self.emit(f"archive_compress(fwd_l1, {ns * neuron.archive_levels}, fwd_out, {ns});")
                self.emit(f"apply_stdp(n->nucleus, {ns}, input, {ns}, fwd_out[0], stdp_lr);")
                self.emit(f"// Hebbian update")
                self.emit(f"apply_hebbian(n->nucleus, {ns}, input, {ns}, fwd_out[0], lr);")
                self.indent -= 1
                self.emit("}")
                self.emit()

    def _emit_neuron_processors(self):
        self.emit("/* ========= Neuron Processors ========= */")
        for neuron in self.module.neurons:
            self._process_neuron(neuron)

    def _emit_regions(self, ev: CEventEmitter):
        for region in self.module.regions:
            count = region.neuron_count
            nt = region.neuron_type
            upper = region.name.upper()
            self.emit(f"#define NUM_NEURONS_{upper} {count}")
            self.emit(f"Neuron_{nt} {region.name}_neurons[{count}];")
            self.emit()
            self.emit(f"void init_region_{region.name}(void) {{")
            self.indent += 1
            self.emit(f"for (int i = 0; i < {count}; i++)")
            self.emit(f"    init_{nt}(&{region.name}_neurons[i]);")
            self.indent -= 1
            self.emit("}")
            self.emit()
            ns = self._neuron_size(nt)
            bptt = CBPTTEmitter(self.emit, self._set_indent)
            bptt.emit_region_bptt(region.name, nt, count, ns, self._steps)
            ev.emit_run_region(region, nt, self._steps)
            ev.emit_step_compat(region, ns, self._steps)
            self.emit()

    def _emit_datasets(self):
        for ds in self.module.datasets:
            safe = re.sub(r"[^A-Za-z0-9_]", "_", ds.name)
            path = self._resolve_data_path(ds.source)
            self.emit(f"char* {safe}_lines[1024];")
            self.emit(f"int {safe}_count = 0;")
            self.emit(f"void load_{safe}(void) {{")
            self.indent += 1
            self.emit(f'FILE* fp = fopen("{path}", "r");')
            self.emit("if (!fp) return;")
            self.emit("char line[512];")
            self.emit(f"while ({safe}_count < 1024 && fgets(line, sizeof(line), fp)) {{")
            self.indent += 1
            self.emit("size_t len = strlen(line);")
            self.emit("if (len > 0 && line[len-1] == '\\n') line[--len] = '\\0';")
            self.emit("if (len == 0) continue;")
            self.emit(f"{safe}_lines[{safe}_count] = (char*)malloc(len + 1);")
            self.emit(f"strcpy({safe}_lines[{safe}_count], line);")
            self.emit(f"{safe}_count++;")
            self.indent -= 1
            self.emit("}")
            self.emit("fclose(fp);")
            self.indent -= 1
            self.emit("}")
            self.emit()
            self.emit(f"void encode_line_{safe}(const char* text, float* out, int out_size) {{")
            self.indent += 1
            self.emit("for (int i = 0; i < out_size; i++) {")
            self.indent += 1
            self.emit(
                "float v = (text && i < (int)strlen(text)) ?"
                " (float)text[i] / 128.0f - 0.5f : 0.0f;"
            )
            self.emit("out[i] = v;")
            self.indent -= 1
            self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.emit()

    def _emit_training(self):
        for train in self.module.train_stmts:
            count = self._region_count(train.region)
            ds = self._dataset_by_name(train.dataset)
            safe = re.sub(r"[^A-Za-z0-9_]", "_", ds.name) if ds else "data"
            ns = self._input_size_for_region(train.region)
            nt = self._neuron_type_for_region(train.region)
            rule = train.rule.lower()
            mode = train.mode.lower()
            lr = train.learning_rate
            stdp_lr = train.stdp_lr
            self.emit(f"void train_{train.region}(void) {{")
            self.indent += 1
            self.emit(f"init_region_{train.region}();")
            if ds:
                self.emit(f"load_{safe}();")
            self.emit(f"float input[{ns}];")
            self.emit(f"float output[{count}];")
            self.emit(f"for (int epoch = 0; epoch < {train.epochs}; epoch++) {{")
            self.indent += 1
            samples = f"{safe}_count" if ds else "16"
            loop_open = (
                f"for (int s = 0; s < {samples}; s++) {{"
                if ds
                else "for (int s = 0; s < 16; s++) {"
            )
            self.emit(loop_open)
            self.indent += 1
            if ds:
                self.emit(f"encode_line_{safe}({safe}_lines[s], input, {ns});")
            else:
                self.emit(f"for (int i = 0; i < {ns}; i++)")
                self.emit("    input[i] = ((float)rand() / RAND_MAX) * 2.0f - 1.0f;")
            self.emit(f"step_region_{train.region}(input, {ns}, output);")
            if mode == "hybrid":
                self.emit(
                    f"bptt_backward_{train.region}(input, {ns}, {lr}f, {stdp_lr}f);"
                )
            elif mode == "online":
                self.emit(f"for (int i = 0; i < {count}; i++) {{")
                self.indent += 1
                self.emit(f"online_step_{nt}(&{train.region}_neurons[i], input, {lr}f, {stdp_lr}f);")
                self.indent -= 1
                self.emit("}")
            else:
                self.emit(f"for (int i = 0; i < {count}; i++) {{")
                self.indent += 1
                if rule == "stdp":
                    self.emit(
                        f"apply_stdp({train.region}_neurons[i].nucleus, {ns},"
                        f" input, {ns}, output[i], {lr}f);"
                    )
                else:
                    self.emit(
                        f"apply_hebbian({train.region}_neurons[i].nucleus, {ns},"
                        f" input, {ns}, output[i], {lr}f);"
                    )
                self.indent -= 1
                self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.emit(
                f'printf("Training complete: %d epochs on {train.region}\\n",'
                f" {train.epochs});"
            )
            self.indent -= 1
            self.emit("}")
            self.emit()

    def _emit_inference(self, ev: CEventEmitter):
        for infer in self.module.infer_stmts:
            count = self._region_count(infer.region)
            ns = self._input_size_for_region(infer.region)
            name = infer.region
            self.emit(f"float infer_{name}(float* input_vec, int input_size) {{")
            self.indent += 1
            self.emit("static int initialized = 0;")
            self.emit(f"if (!initialized) {{ init_region_{name}(); initialized = 1; }}")
            self.emit("event_head = 0;")
            self.emit("event_tail = 0;")
            self.emit(f"inject_input({name}_event_q, &event_head, &event_tail,")
            self.emit("    input_vec, input_size, 0);")
            self.emit(f"run_region_{name}({self._steps});")
            self.emit("float result = 0.0f;")
            self.emit(f"for (int i = 0; i < {count}; i++) result += {name}_neurons[i].output;")
            self.emit(f"return result / (float){count};")
            self.indent -= 1
            self.emit("}")
            self.emit()

    def _emit_main(self, ev: CEventEmitter):
        ns = self.module.neurons[0].nucleus_size if self.module.neurons else 16
        self.emit("int main(void) {")
        self.indent += 1
        self.emit("srand((unsigned int)time(NULL));")
        self.emit(f'printf("Million Runtime v{__version__} (event-driven)\\n");')
        for train in self.module.train_stmts:
            self.emit(f"train_{train.region}();")
        if self.module.infer_stmts:
            self.emit('printf("=== Spiking Chat (event-driven) ===\\n");')
            self.emit(f"float input[{ns}];")
            self.emit("char buffer[256];")
            self.emit("while (1) {")
            self.indent += 1
            self.emit('printf("\\nYou: ");')
            self.emit("if (!fgets(buffer, sizeof(buffer), stdin)) break;")
            self.emit("if (buffer[0] == 'q' || buffer[0] == '\\n') break;")
            self.emit(f"for (int i = 0; i < {ns}; i++) {{")
            self.indent += 1
            self.emit(
                "input[i] = (i < (int)strlen(buffer)) ?"
                " (float)buffer[i] / 128.0f - 0.5f : 0.0f;"
            )
            self.indent -= 1
            self.emit("}")
            for infer in self.module.infer_stmts:
                self.emit(f"float result = infer_{infer.region}(input, {ns});")
                self.emit('printf("Million: %c (confidence: %.3f)\\n",')
                self.indent += 2
                self.emit("(char)((int)((result + 1.0f) * 64.0f) % 95 + 32), result);")
                self.indent -= 2
            self.indent -= 1
            self.emit("}")
        self.emit('printf("\\nGoodbye!\\n");')
        self.emit("return 0;")
        self.indent -= 1
        self.emit("}")

    def _type_to_c(self, type_name: str) -> str:
        mapping = {
            "int": "int",
            "f32": "float",
            "bool": "int",
            "string": "const char*",
            "void": "void",
        }
        if type_name in mapping:
            return mapping[type_name]
        if type_name.startswith("tensor"):
            return "float"
        return type_name

    def _expr_to_c(self, node) -> str:
        if node is None:
            return "0"
        kind = getattr(node, "kind", None) or type(node).__name__
        if kind == "Literal" or hasattr(node, "value"):
            val = node.value
            if isinstance(val, bool):
                return "1" if val else "0"
            if isinstance(val, str):
                return f'"{val}"'
            if isinstance(val, float):
                return f"{val}f"
            return str(val)
        if kind == "Identifier" or hasattr(node, "name"):
            return node.name
        if kind == "BinaryOp" or (hasattr(node, "left") and hasattr(node, "right")):
            left = self._expr_to_c(node.left)
            right = self._expr_to_c(node.right)
            op = node.op
            return f"({left} {op} {right})"
        if kind == "UnaryOp" or (hasattr(node, "operand") and hasattr(node, "op")):
            operand = self._expr_to_c(node.operand)
            op = node.op
            if op == "!":
                return f"(!{operand})"
            return f"({op}{operand})"
        if kind == "Call" or hasattr(node, "callee"):
            callee = node.callee if hasattr(node, "callee") else node.name
            args = ", ".join(self._expr_to_c(a) for a in node.args)
            return f"{callee}({args})"
        return str(node)

    def _emit_function(self, node):
        return_type = self._type_to_c(node.return_type if node.return_type else "void")
        params = []
        for p_name, p_type in node.params:
            ptype = self._type_to_c(p_type)
            params.append(f"{ptype} {p_name}")
        param_str = ", ".join(params)
        self.emit(f"{return_type} {node.name}({param_str}) {{")
        self.indent += 1
        self._emit_block(node.body)
        self.indent -= 1
        self.emit("}")
        self.emit()

    def _emit_if_stmt(self, node):
        cond = self._expr_to_c(node.condition)
        self.emit(f"if ({cond}) {{")
        self.indent += 1
        self._emit_block(node.then_block)
        self.indent -= 1
        if node.else_block:
            self.emit("} else {")
            self.indent += 1
            self._emit_block(node.else_block)
            self.indent -= 1
        self.emit("}")

    def _emit_for_stmt(self, node):
        start = self._expr_to_c(node.start) if node.start else "0"
        end = self._expr_to_c(node.end) if node.end else "0"
        self.emit(f"for (int {node.var} = {start}; {node.var} < {end}; {node.var}++) {{")
        self.indent += 1
        self._emit_block(node.body)
        self.indent -= 1
        self.emit("}")

    def _emit_while_stmt(self, node):
        cond = self._expr_to_c(node.condition)
        self.emit(f"while ({cond}) {{")
        self.indent += 1
        self._emit_block(node.body)
        self.indent -= 1
        self.emit("}")

    def _emit_return(self, node):
        if node.value:
            val = self._expr_to_c(node.value)
            self.emit(f"return {val};")
        else:
            self.emit("return;")

    def _emit_var_decl(self, node):
        if node.value:
            typ = self._type_to_c(node.type.name if node.type else "f32")
            val = self._expr_to_c(node.value)
            self.emit(f"{typ} {node.name} = {val};")
        else:
            typ = self._type_to_c(node.type.name if node.type else "f32")
            self.emit(f"{typ} {node.name};")

    def _emit_block(self, stmts):
        if isinstance(stmts, list):
            for stmt in stmts:
                self._emit_stmt(stmt)
        elif hasattr(stmts, "statements"):
            for stmt in stmts.statements:
                self._emit_stmt(stmt)

    def _emit_stmt(self, node):
        if node is None:
            return
        kind = getattr(node, "kind", None) or type(node).__name__
        if kind == "VarDecl":
            self._emit_var_decl(node)
        elif kind == "IfStmt":
            self._emit_if_stmt(node)
        elif kind == "ForStmt":
            self._emit_for_stmt(node)
        elif kind == "WhileStmt":
            self._emit_while_stmt(node)
        elif kind == "ReturnStmt":
            self._emit_return(node)
        elif kind == "Block":
            self._emit_block(node)
        elif kind == "ExprStmt":
            val = self._expr_to_c(node.value)
            self.emit(f"{val};")
        else:
            val = self._expr_to_c(node)
            self.emit(f"{val};")

    def _emit_functions(self):
        if not self.module.functions:
            return
        self.emit("/* ========= User Functions ========= */")
        for func in self.module.functions:
            self._emit_function(func)

    def _neuron_size(self, name: str) -> int:
        for n in self.module.neurons:
            if n.name == name:
                return n.nucleus_size
        return 16

    def _neuron_type_for_region(self, region_name: str) -> str:
        for r in self.module.regions:
            if r.name == region_name:
                return r.neuron_type
        return ""

    def _input_size_for_region(self, region_name: str) -> int:
        nt = self._neuron_type_for_region(region_name)
        return self._neuron_size(nt) if nt else 16

    def _region_count(self, name: str) -> int:
        for r in self.module.regions:
            if r.name == name:
                return r.neuron_count
        return 100

    def _dataset_by_name(self, name: str):
        for d in self.module.datasets:
            if d.name == name:
                return d
        return None

    def _resolve_data_path(self, source: str) -> str:
        p = Path(source)
        if p.is_absolute():
            return str(p).replace("\\", "/")
        root = Path(__file__).resolve().parent.parent.parent
        for base in (self.source_dir, root, root / "examples", root / "data"):
            candidate = base / source
            if candidate.is_file():
                return str(candidate.resolve()).replace("\\", "/")
        return str((self.source_dir / source).resolve()).replace("\\", "/")
