class CCodeGen:
    def __init__(self, mir_module):
        self.module = mir_module
        self.indent = 0
        self.lines = []

    def emit(self, line: str = ""):
        prefix = "    " * self.indent if line else ""
        self.lines.append(f"{prefix}{line}")

    def emit_block(self, block: list[str]):
        for line in block:
            self.emit(line)

    def generate(self) -> str:
        self.emit("/* ======================================== */")
        self.emit("/*  Generated by Million Compiler v0.1     */")
        self.emit("/*  Language: Million → C                  */")
        self.emit("/* ======================================== */")
        self.emit()
        self.emit('#include <stdlib.h>')
        self.emit('#include <string.h>')
        self.emit('#include <math.h>')
        self.emit('#include <time.h>')
        self.emit()

        # Types
        self.emit("/* ============== Types ============== */")
        self.emit("typedef struct { float* data; int size; int levels; } Archive;")
        self.emit("typedef struct { float potential; float threshold; float refractory; int refr_counter; } Membrane;")
        self.emit()

        # Forward declarations for neurons
        for neuron in self.module.neurons:
            self.emit(f"typedef struct Neuron_{neuron.name} Neuron_{neuron.name};")
        self.emit()

        # Neuron structs
        for neuron in self.module.neurons:
            self.emit(f"/* ----- Neuron: {neuron.name} ----- */")
            self.emit(f"struct Neuron_{neuron.name} {{")
            self.indent += 1
            self.emit(f"float nucleus[{neuron.nucleus_size}];")
            self.emit(f"int archive_levels;")
            self.emit(f"Membrane mem;")
            self.emit(f"float output;")
            self.indent -= 1
            self.emit("};")
            self.emit()

        # Neuron init functions
        for neuron in self.module.neurons:
            self.emit(f"void init_{neuron.name}(struct Neuron_{neuron.name}* n) {{")
            self.indent += 1
            self.emit(f"memset(n->nucleus, 0, sizeof(n->nucleus));")
            self.emit(f"n->archive_levels = {neuron.archive_levels};")
            self.emit(f"n->mem.potential = {neuron.membrane_potential}f;")
            self.emit(f"n->mem.threshold = 1.0f;")
            self.emit(f"n->mem.refractory = {neuron.refractory_period}f;")
            self.emit(f"n->mem.refr_counter = 0;")
            self.emit(f"n->output = 0.0f;")
            self.indent -= 1
            self.emit("}")
            self.emit()

        # Archive operations
        self.emit("/* ========= Archive Operations ========= */")
        self.emit("void archive_unfold(float* in, int in_size, float* out, int out_size, int level) {")
        self.indent += 1
        self.emit("for (int i = 0; i < out_size; i++) {")
        self.indent += 1
        self.emit("float sum = 0.0f;")
        self.emit("for (int j = 0; j < in_size; j++) {")
        self.indent += 1
        self.emit("sum += in[j] * sinf((float)(i * j + level));")
        self.indent -= 1
        self.emit("}")
        self.emit("out[i] = tanhf(sum / in_size);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()

        self.emit("void archive_compress(float* in, int in_size, float* out, int out_size) {")
        self.indent += 1
        self.emit("int group = in_size / out_size;")
        self.emit("for (int i = 0; i < out_size; i++) {")
        self.indent += 1
        self.emit("float sum = 0.0f;")
        self.emit("int start = i * group;")
        self.emit("for (int j = 0; j < group; j++) {")
        self.indent += 1
        self.emit("sum += in[start + j];")
        self.indent -= 1
        self.emit("}")
        self.emit("out[i] = tanhf(sum / group);")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()

        # Process function
        for neuron in self.module.neurons:
            self.emit(f"void process_{neuron.name}(struct Neuron_{neuron.name}* n, float* input_vec, int input_size) {{")
            self.indent += 1

            if neuron.dynamics:
                self.emit(f"int l1_size = n->archive_levels * {neuron.nucleus_size};")
                self.emit(f"float* level1 = (float*)malloc(l1_size * sizeof(float));")
                self.emit(f"archive_unfold(n->nucleus, {neuron.nucleus_size}, level1, l1_size, 1);")
                self.emit()
                self.emit(f"int l2_size = l1_size * {neuron.nucleus_size};")
                self.emit(f"float* level2 = (float*)malloc(l2_size * sizeof(float));")
                self.emit(f"archive_unfold(level1, l1_size, level2, l2_size, 2);")
                self.emit()
                self.emit(f"float compressed[{neuron.nucleus_size}];")
                self.emit(f"archive_compress(level2, l2_size, compressed, {neuron.nucleus_size});")
                self.emit()

            self.emit("/* Membrane dynamics */")
            self.emit("if (n->mem.refr_counter > 0) {")
            self.indent += 1
            self.emit("n->mem.refr_counter--;")
            self.emit("n->output = 0.0f;")
            self.emit("free(level1); free(level2);")
            self.emit("return;")
            self.indent -= 1
            self.emit("}")
            self.emit()

            if neuron.dynamics:
                self.emit("/* Apply dynamics: integrate input with compressed state */")
                self.emit("float delta = 0.0f;")
                self.emit("for (int i = 0; i < input_size && i < l2_size; i++) {")
                self.indent += 1
                self.emit("delta += input_vec[i] * compressed[i % 16];")
                self.indent -= 1
                self.emit("}")
                self.emit("n->mem.potential += delta / input_size;")

            self.emit()
            self.emit("if (n->mem.potential >= n->mem.threshold) {")
            self.indent += 1
            self.emit("n->output = n->mem.potential;")
            self.emit("n->mem.potential = 0.0f;")
            self.emit("n->mem.refr_counter = (int)n->mem.refractory;")
            self.emit()
            self.emit("/* Adaptive threshold */")
            self.emit("n->mem.threshold = 0.5f + (n->mem.threshold - 0.5f) * 0.9f + 0.1f * fabsf(n->output);")

            self.indent -= 1
            self.emit("} else {")
            self.indent += 1
            self.emit("n->output = 0.0f;")
            self.emit("/* Leak */")
            self.emit("n->mem.potential *= 0.95f;")
            self.indent -= 1
            self.emit("}")

            if neuron.dynamics:
                self.emit()
                self.emit("/* Update nucleus (learn) */")
                self.emit("for (int i = 0; i < 16 && i < input_size; i++) {")
                self.indent += 1
                self.emit("n->nucleus[i] += 0.01f * input_vec[i] * n->output;")
                self.emit("n->nucleus[i] = tanhf(n->nucleus[i]);")
                self.indent -= 1
                self.emit("}")

            if neuron.dynamics:
                self.emit("free(level1); free(level2);")

            self.indent -= 1
            self.emit("}")
            self.emit()

        # Main function with region simulation
        for region in self.module.regions:
            self.emit(f"/* ----- Region: {region.name} ----- */")
            self.emit(f"#define NUM_NEURONS_{region.name.upper()} {region.neuron_count}")
            self.emit()
            self.emit(f"struct Neuron_{region.neuron_type} {region.name}_neurons[{region.neuron_count}];")
            self.emit()
            self.emit(f"void init_region_{region.name}() {{")
            self.indent += 1
            self.emit(f"for (int i = 0; i < {region.neuron_count}; i++) {{")
            self.indent += 1
            self.emit(f"init_{region.neuron_type}(&{region.name}_neurons[i]);")
            self.indent -= 1
            self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.emit()

            # Process all neurons
            self.emit(f"void step_region_{region.name}(float* input, int input_size, float* output) {{")
            self.indent += 1
            self.emit(f"for (int i = 0; i < {region.neuron_count}; i++) {{")
            self.indent += 1
            self.emit(f"process_{region.neuron_type}(&{region.name}_neurons[i], input, input_size);")
            self.emit(f"output[i] = {region.name}_neurons[i].output;")
            self.indent -= 1
            self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.emit()

        # Training loop
        for train in self.module.train_stmts:
            self.emit(f"/* ----- Training: {train.region} on {train.dataset} ----- */")
            self.emit(f"void train_{train.region}() {{")
            self.indent += 1
            self.emit(f"init_region_{train.region}();")
            self.emit(f"float input[16];")
            self.emit(f"float output[{self._region_count(train.region)}];")
            self.emit()
            self.emit(f"for (int epoch = 0; epoch < {train.epochs}; epoch++) {{")
            self.indent += 1
            self.emit("/* Generate random input for demo */")
            self.emit("for (int i = 0; i < 16; i++) {")
            self.indent += 1
            self.emit("input[i] = ((float)rand() / RAND_MAX) * 2.0f - 1.0f;")
            self.indent -= 1
            self.emit("}")
            self.emit("step_region_" + train.region + "(input, 16, output);")
            self.indent -= 1
            self.emit("}")
            self.indent -= 1
            self.emit("}")
            self.emit()

        # Chat inference
        for infer in self.module.infer_stmts:
            self.emit(f"/* ----- Inference: {infer.region} on {infer.input_var} ----- */")
            self.emit(f"float infer_{infer.region}(float* input_vec, int input_size) {{")
            self.indent += 1
            self.emit(f"static int initialized = 0;")
            self.emit(f"if (!initialized) {{ init_region_{infer.region}(); initialized = 1; }}")
            self.emit(f"float output[{self._region_count(infer.region)}];")
            self.emit(f"step_region_{infer.region}(input_vec, input_size, output);")
            self.emit(f"/* Aggregate output */")
            self.emit(f"float result = 0.0f;")
            self.emit(f"for (int i = 0; i < {self._region_count(infer.region)}; i++) {{")
            self.indent += 1
            self.emit("result += output[i];")
            self.indent -= 1
            self.emit("}")
            self.emit(f"return result / {self._region_count(infer.region)};")
            self.indent -= 1
            self.emit("}")
            self.emit()

        # Main
        self.emit("int main() {")
        self.indent += 1
        self.emit('srand((unsigned int)time(NULL));')
        self.emit('printf("Million Runtime v0.1\\n");')
        self.emit('printf("=== Chat Demo ===\\n");')
        self.emit()
        self.emit('float input[16];')
        self.emit('char buffer[256];')
        self.emit()
        self.emit('while (1) {')
        self.indent += 1
        self.emit('printf("\\nYou: ");')
        self.emit('if (!fgets(buffer, sizeof(buffer), stdin)) break;')
        self.emit('if (buffer[0] == \'q\' || buffer[0] == \'\\n\') break;')
        self.emit()
        self.emit('/* Encode input char to neuron state */')
        self.emit('for (int i = 0; i < 16; i++) {')
        self.indent += 1
        self.emit('input[i] = (i < (int)strlen(buffer)) ? (float)buffer[i] / 128.0f - 0.5f : 0.0f;')
        self.indent -= 1
        self.emit('}')

        for infer in self.module.infer_stmts:
            self.emit()
            self.emit(f'float result = infer_{infer.region}(input, 16);')
            self.emit(f'printf("Million: %c (confidence: %.3f)\\n",')
            self.indent += 2
            self.emit('(char)((int)((result + 1.0f) * 64.0f) % 95 + 32), result);')
            self.indent -= 2

        self.indent -= 1
        self.emit("}")
        self.emit()
        self.emit('printf("\\nGoodbye!\\n");')
        self.emit("return 0;")
        self.indent -= 1
        self.emit("}")
        self.emit()

        return "\n".join(self.lines)

    def _region_count(self, name: str) -> int:
        for r in self.module.regions:
            if r.name == name:
                return r.neuron_count
        return 100
